namespace: argocd

resources:
  - route-http.yaml
  - route-grpc.yaml
  - apps/xmoto-web-api/app-staging.yaml
  - apps/xmoto-web-api/app-prod.yaml
  - apps/xmoto-web-site/app-staging.yaml
  - apps/xmoto-web-site/app-prod.yaml
