apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: xmoto-web-site-staging

spec:
  project: default

  source:
    repoURL: https://github.com/xmoto/argocd-deployments.git
    targetRevision: HEAD
    path: xmoto-web-site/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
