repositories:
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns

releases:
  - name: external-dns
    namespace: external-dns
    chart: external-dns/external-dns
    values:
      - values/external-dns.yaml
