provider:
  name: cloudflare

sources:
  - gateway-httproute

domainFilters:
  - xmoto.org

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token

extraArgs:
  - --cloudflare-proxied
  - --cloudflare-dns-records-per-page=5000
  - --cloudflare-record-comment="provisioned by external-dns"
